# Software Install
- enable_restricted: true
- install_recommends: false

- configure_apt_to_use_less_disk_space:
  - write_in:
    - /etc/apt/apt.conf.d/02compress_indexes
    - |
      Acquire::GzipIndexes "true";
      Acquire::CompressionTypes::Order:: "gz";
  - exec_in: |
      if [ $$install_recommends = false ]; then
        echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/01norecommend
        echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/01norecommend
      fi
  - write_in:
    - /etc/apt/apt.conf.d/02nocache
    - |
      Dir::Cache {
        srcpkgcache "";
        pkgcache "";
      }
  - write_in:
    - /etc/dpkg/dpkg.cfg.d/01_nodoc
    - |
      path-exclude /usr/share/doc/*
      # we need to keep copyright files for legal reasons
      path-include /usr/share/doc/*/copyright
      path-exclude /usr/share/man/*
      path-exclude /usr/share/groff/*
      path-exclude /usr/share/info/*
      # lintian stuff is small, but really unnecessary
      path-exclude /usr/share/lintian/*
      path-exclude /usr/share/linda/*
      path-exclude /usr/share/locale/*
      path-include /usr/share/locale/en*
  - write_in:
    - /etc/locale.nopurge
    - |
      MANDELETE
      DONTBOTHERNEWLOCALE
      SHOWFREEDSPACE
      #QUICKNDIRTYCALC
      #VERBOSE

- enable_universe_and_multiverse:
  - write_out:
    - $$rootfs_download_path/etc/apt/sources.list
    - |
      deb $$repository $$release main universe multiverse

- enable_restricted:
  - exec_in: |
      if [ $$enable_restricted = true ]; then
        REPO_RESTRICTED="restricted"
      fi
  - exec_in: perl -pi -e "s/multiverse$/multiverse $REPO_RESTRICTED/" /etc/apt/sources.list

- update_repositories:
  - exec_in: apt-get -y --force-yes update
  - exec_in: apt-get -y --force-yes install localepurge
  - on_setup_clean:
    - exec_in: apt-get -y --force-yes autoclean
    - exec_in: apt-get -y --force-yes clean
    - exec_in: apt-get -y --force-yes autoremove
    - exec_in: localepurge

