driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['../../..', '/home/vagrant/kameleon']
    - ['../../../pkg/%{instance_name}', '/var/cache/omnibus/pkg', 'create: true']

provisioner:
  require_chef_omnibus: 11.8.0

platforms:
  - name: ubuntu-12.04
    run_list: apt::default
  - name: centos-5.10

suites:
  - name: default
    run_list: omnibus::default
    attributes:
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/kameleon
        install_dir: /opt/kameleon
