# # System Config
- locales:
  - write_file:
    - /etc/locale.conf
    - |
      LC_COLLATE="C"
      LC_ALL="en_US.UTF-8"
      LC_LANG="en_US.UTF-8"
      LC_MESSAGES="en_US.UTF-8"
  - write_file:
    - /etc/locale.gen
    - |
      en_US.UTF-8 UTF-8
      en_US ISO-8859-1
      # fr_FR.UTF-8 UTF-8
      # fr_FR ISO-8859-1
  - exec_in: locale-gen
  - exec_in: source /etc/locale.conf

- set_hosts:
  - write_file:
    - /etc/hosts
    - |
      #
      # /etc/hosts: static lookup table for host names
      #

      #<ip-address>	<hostname.domain.org>	<hostname>
      127.0.0.1	localhost.localdomain	localhost	$$network_hostname
      ::1		localhost.localdomain	localhost

- set_hostname:
  - exec_in: echo "$$network_hostname" > /etc/hostname
  - exec_in: echo "$$network_hostname" > /etc/hostname

- set_timezone:
  - exec_in: echo "$$timezone" > /etc/timezone
  - exec_in: dpkg-reconfigure -f noninteractive tzdata

- keyboard_config:
  - write_file:
    - /etc/default/keyboard
    - |
      XKBMODEL="pc105"
      XKBLAYOUT="$$keyboard_layout"
      XKBVARIANT=""
      XKBOPTIONS=""
