# # Keyboard Azerty Config
- install_console_tools:
  # FIXME this should use a kind of step include 
  - exec_in: |
      DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes update
  - exec_in: |
      DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes install \
        console-tools console-data console-setup
  - on_clean:
    - exec_in: apt-get clean
  - write_file:
    - /etc/default/keyboard 
    - |
      XKBMODEL="pc105"
      XKBLAYOUT="fr,us"
      XKBVARIANT=""
      XKBOPTIONS=""
