network_config:
  - network_interfaces:
    - write_file:
      - /etc/network/interfaces
      - |
        auto lo
        iface lo inet loopback
        
        auto eth0
        iface eth0 inet dhcp
            pre-up ip link set mtu 1492 eth0
