system_config:
  - locales:
    - write_file:
      - /etc/locale.conf
      - |
        LC_COLLATE="C"
        LC_ALL="en_US.UTF-8"
        LC_LANG="en_US.UTF-8"
        LC_MESSAGES="en_US.UTF-8"
    - write_file:
      - /etc/locale.gen
      - |
        en_US.UTF-8 UTF-8
        en_US ISO-8859-1
        # fr_FR.UTF-8 UTF-8
        # fr_FR ISO-8859-1
    - exec_chroot: locale-gen
    - exec_appliance: source etc/locale.conf
  - etc_hosts:
    - write_file:
       - /etc/hosts
       - 127.0.0.1  localhost $$network_hostname
  - etc_hostname:
    - write_file:
      - /etc/hostname
      - $$network_hostname
  - network_interfaces:
    - write_file:
      - /etc/network/interfaces
      - |
        auto lo
        iface lo inet loopback

        auto eth0
        iface eth0 inet dhcp
  - add_contribs_source:
    - exec_appliance: perl -pi -e "s/main$/main contrib non-free/" etc/apt/sources.list
