# System configuration for Archlinux
#
# This will set the locals and the timezone

- set_locales:
  # uncomment the locales
  - exec_in: |
      echo $$locales | tr ' ' '\n' | xargs -I {} localedef -v -c -i {} -i {} -f UTF-8 $$lang || :

- set_timezone:
  - exec_in: ln -s /usr/share/zoneinfo/$$timezone /etc/localtime
