# System configuration
#
# This will set the locals and the timezone

- set_locales:
  # uncomment the locales
  - exec_in: |
      echo $$locales | tr ' ' '\n' | xargs -I {} localedef -v -c -i {} -i {} -f UTF-8 $$lang 2>&1 || :

- set_timezone:
  - exec_in: ln -sf /usr/share/zoneinfo/$$timezone /etc/localtime

- set_wheel_sudo:
  - exec_in: echo "%wheel      ALL=(ALL) ALL" >> /etc/sudoers

- remove_random_seed:
  - exec_in: echo "Removing random-seed so it's not the same in every image."
  - exec_in: rm -f /var/lib/random-seed

- compress_cracklib:
  - exec_in: gzip -9 /usr/share/cracklib/pw_dict.pwd
