- update_hostfile:
  - append_in:
    - /etc/hosts
    - |
      127.0.0.2 node1 node2

- create_resources:
  - exec_in: /usr/local/sbin/oarproperty -a core
  - exec_in: /usr/local/sbin/oarproperty -a cpu
  - exec_in: /usr/local/sbin/oarnodesetting -a -h node1 -p cpu=0 -p core=0 -p cpuset=0
  - exec_in: /usr/local/sbin/oarnodesetting -a -h node1 -p cpu=0 -p core=1 -p cpuset=0
  - exec_in: /usr/local/sbin/oarnodesetting -a -h node1 -p cpu=1 -p core=2 -p cpuset=0
  - exec_in: /usr/local/sbin/oarnodesetting -a -h node1 -p cpu=1 -p core=3 -p cpuset=0
  - exec_in: /usr/local/sbin/oarnodesetting -a -h node2 -p cpu=2 -p core=4 -p cpuset=0
  - exec_in: /usr/local/sbin/oarnodesetting -a -h node2 -p cpu=2 -p core=5 -p cpuset=0
  - exec_in: /usr/local/sbin/oarnodesetting -a -h node2 -p cpu=3 -p core=6 -p cpuset=0
  - exec_in: /usr/local/sbin/oarnodesetting -a -h node2 -p cpu=3 -p core=7 -p cpuset=0

- modify_job_resource_manager:
  - exec_in: sed -e 's/#exit/exit/' -i /etc/oar/job_resource_manager.pl
  - exec_in: sed -i 's/job_resource_manager_cgroups\.pl/job_resource_manager\.pl/g' /etc/oar/oar.conf
